services:
  oebb-puppeteer:
    build:
      context: ./oebb-puppeteer
    container_name: oebb-puppeteer
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_FILE=/app/data/database_2.sqlite
      - SCREENSHOT_PATH=/app/screenshots
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./screenshots:/app/screenshots
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.oebb-puppeteer-http.rule=Host(`oebb-puppeteer.hafen.dakantz.at`)
      - traefik.http.routers.oebb-puppeteer-http.entrypoints=http
      - traefik.http.services.oebb-puppeteer.loadbalancer.server.port=3000
      # - traefik.http.routers.oebb-puppeteer-http.middlewares=redirect
      # - traefik.http.routers.oebb-puppeteer-https.rule=Host(`oebb-puppeteer.hafen.dakantz.at`)
      # - traefik.http.routers.oebb-puppeteer-https.entrypoints=https
      # - traefik.http.routers.oebb-puppeteer-https.tls=true
      # - traefik.http.routers.oebb-puppeteer-https.tls.certresolver=letsencrypt
      # - traefik.http.middlewares.redirect.redirectscheme.scheme=https
    networks:
      - web
    security_opt:
      - seccomp=unconfined # Needed for Chrome to run in a container
    # Uncomment the following lines if you need to run the container in a non-privileged mode
    # cap_add:
    #   - SYS_ADMIN
networks:
  web:
    external: true